const DATA = [
  {
    task: "Buy Groceries",
    due: "2024/06/15",
    notes: "Get milk, eggs, and bread",
    priority: "High",
    completed: false,
  },
  {
    task: "Clean the House",
    due: null,
    notes: "Vacuum and dust living room",
    priority: "Medium",
    completed: false,
  },
  {
    task: "Schedule Doctor Appointment",
    due: null,
    notes: "",
    priority: "High",
    completed: false,
  },
  {
    task: "Pay Utility Bills",
    due: "2024/05/10",
    notes: "Electricity and water bills",
    priority: "High",
    completed: true,
  },
  {
    task: "Organize Garage",
    due: null,
    notes: "",
    priority: "Low",
    completed: false,
  },
  {
    task: "Plan Birthday Party",
    due: "2024/07/01",
    notes: "Send invitations and order cake",
    priority: "Medium",
    completed: false,
  },
  {
    task: "Water the Plants",
    due: null,
    notes: "Indoor and outdoor plants",
    priority: "Low",
    completed: false,
  },
  {
    task: "Fix Leaky Faucet",
    due: null,
    notes: "Kitchen sink faucet",
    priority: "High",
    completed: false,
  },
  {
    task: "Walk the Dog",
    due: "2024/05/20",
    notes: "30-minute walk in the park",
    priority: "Medium",
    completed: true,
  },
  {
    task: "Read a Book",
    due: "2024/05/25",
    notes: "Finish reading 'To Kill a Mockingbird'",
    priority: "Low",
    completed: false,
  },
  {
    task: "Meal Prep for the Week",
    due: null,
    notes: "Prepare lunches and dinners",
    priority: "Medium",
    completed: false,
  },
  {
    task: "Take Car for Service",
    due: "2024/06/10",
    notes: "Oil change and tire rotation",
    priority: "High",
    completed: false,
  },
];

export default DATA;
